project:
  type: website
  output-dir: docs

website:
  title: "Jeanie's Personal Site"
  favicon: project.png
  navbar:
    logo: nav.jpg
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: datavis.qmd
        text: Data Visualization
      - href: reflection.html
        text: Reflection

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left

editor: visual

