project:
  type: website
  output-dir: docs

website:
  title: "Jeanie's Personal Site"
  favicon: (img\project.jpg)
  navbar:
    logo: (img\nav.jpg)
    left:
      - href: index.qmd
        text: Home
      - about.qmd
<<<<<<< HEAD
      - href: DataVis.qmd
        text: Data Visualization
      - href: Reflection.html
=======
      - href: datavis.qmd
        text: Data Visualization
      - href: reflection.html
>>>>>>> f1a6d31abf54287acc6f3fb874f864948381c7ae
        text: Reflection

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left

editor: visual
